import turtle

shuchen = turtle.Turtle()
shuchen.speed(50)

# shuchen.forward(100)
# shuchen.right(60)
# shuchen.forward(100)
# shuchen.right(60)
# shuchen.forward(100)

shuchen.color("#555455", "#C4BDC1")

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)


shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)


shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(20)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)


shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)


shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(20)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(20)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)


shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)


shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(30)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(40)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.begin_fill()

shuchen.penup()
shuchen.left(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(300)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(50)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(20)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.right(60)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(100)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.backward(200)
shuchen.pendown()

shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()

shuchen.penup()
shuchen.forward(90)
shuchen.pendown()

shuchen.begin_fill()
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.left(90)
shuchen.forward(100)
shuchen.end_fill()




turtle.done()